options:
  client-port:
    description: Zookeeper client port
    type: int
    default: 2181
  server-port:
    description: Zookeeper server port
    type: int
    default: 2888
  leader-port:
    description: Zookeeper leader-election port
    type: int
    default: 3888
  image:
    description: Docker image name
    type: string
    default: zookeeper
  version:
    description: Zookeeper version to use
    type: string
    default: 3.5.8
  tick-time:
    description: |
      The length of a single tick, which is the basic time unit used by ZooKeeper,
      as measured in milliseconds. It is used to regulate heartbeats, and timeouts.
      For example, the minimum session timeout will be two ticks.
    type: int
    default: 2000
  init-limit:
    description: |
      Amount of time, in ticks (see tickTime), to allow followers to connect
      and sync to a leader. Increased this value as needed, 
      if the amount of data managed by ZooKeeper is large.
    type: int
    default: 5
  sync-limit:
    description: |
      Amount of time, in ticks (see tickTime), to allow followers to sync
      with ZooKeeper. If followers fall too far behind a leader,they will be dropped.
    type: int
    default: 2
  max-client-cnxns:
    description: |
      Limits the number of concurrent connections (at the socket level) 
      that a single client, identified by IP address, may make to a single member 
      of the ZooKeeper ensemble.
    type: int
    default: 60
  adminserver-enabled:
    description: |
      New in 3.5.0: The AdminServer is an embedded Jetty server that provides
      an HTTP interface to the four letter word commands. 
      By default, the server is started on port 8080, and commands are issued
      by going to the URL "/commands/[command name]",
      e.g., http://localhost:8080/commands/stat.
    type: boolean
    default: true
  purge-interval:
    description: |
      The time interval in hours for which the purge task has to be triggered.
      Set to a positive integer (1 and above) to enable the auto purging.
    type: int
    default: 0
  snap-retain-count:
    description: |
      When enabled, ZooKeeper auto purge feature retains the
      autopurge.snapRetainCount most recent snapshots and the corresponding
      transaction logs in the dataDir and dataLogDir respectively and deletes the rest.
      Defaults to 3. Minimum value is 3.
    type: int
    default: 3
  4lw-commands-whitelist:
    description: |
      A list of comma separated Four Letter Words commands that user wants to use.
      A valid Four Letter Words command must be put in this list else
      ZooKeeper server will not enable the command.
      By default the whitelist only contains "srvr" command which zkServer.sh uses.
      The rest of four letter word commands are disabled by default.
    type: string
    default: srvr
  heap:
    description: Heap memory
    type: string
    default: 512M
  max-session-timeout:
    description: Max session timeout
    type: int
    default: 40000
  min-session-timeout:
    description: Min session timeout
    type: int
    default: 4000
  log-level:
    description: Log level
    type: string
    default: INFO
